name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install Dependencies
        run: dotnet restore

      - name: Build SecureWeb
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Run Code Analysis
        uses: github/codeql-action/analyze@v2

      - name: Check for vulnerabilities
        run: dotnet list package --vulnerable --include-transitive

      - name: Publish Artifacts
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./publish
